# Persistent storage for uploaded product/profile images.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kardamom-media
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-sc"
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 2Gi
