# ClusterIP Service: kube-proxy load-balances traffic across the 3 replicas.
apiVersion: v1
kind: Service
metadata:
  name: kardamom
  labels:
    app: kardamom
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: kardamom
  ports:
    - name: http
      port: 80
      targetPort: 8000
