# Generated by Django 6.1.1 on 2026-09-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(help_text='Display name. Need not be unique.', max_length=150, verbose_name='display name'),
        ),
    ]
