# Generated by Django 6.1.1 on 2026-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g. Alleppey Green, Bold 8mm', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Size in mm, e.g. 8.0', max_digits=5, null=True),
        ),
    ]
